# Generated by Django 3.1.7 on 2021-03-05 22:42

from django.db import migrations, models
import jornal.models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='capa',
            field=models.ImageField(null=True, upload_to=jornal.models.noticia_capa_directory_path),
        ),
    ]
